/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonType } from "./components/fs-button/fs-button";
export { ButtonType } from "./components/fs-button/fs-button";
export namespace Components {
    interface FsButton {
        /**
          * @default 'primary'
         */
        "type": ButtonType;
    }
    interface FsInput {
    }
}
declare global {
    interface HTMLFsButtonElement extends Components.FsButton, HTMLStencilElement {
    }
    var HTMLFsButtonElement: {
        prototype: HTMLFsButtonElement;
        new (): HTMLFsButtonElement;
    };
    interface HTMLFsInputElement extends Components.FsInput, HTMLStencilElement {
    }
    var HTMLFsInputElement: {
        prototype: HTMLFsInputElement;
        new (): HTMLFsInputElement;
    };
    interface HTMLElementTagNameMap {
        "fs-button": HTMLFsButtonElement;
        "fs-input": HTMLFsInputElement;
    }
}
declare namespace LocalJSX {
    interface FsButton {
        /**
          * @default 'primary'
         */
        "type"?: ButtonType;
    }
    interface FsInput {
    }
    interface IntrinsicElements {
        "fs-button": FsButton;
        "fs-input": FsInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fs-button": LocalJSX.FsButton & JSXBase.HTMLAttributes<HTMLFsButtonElement>;
            "fs-input": LocalJSX.FsInput & JSXBase.HTMLAttributes<HTMLFsInputElement>;
        }
    }
}
