/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonType } from "./components/fs-button/fs-button";
import { Theme } from "./context/theme";
export { ButtonSize, ButtonType } from "./components/fs-button/fs-button";
export { Theme } from "./context/theme";
export namespace Components {
    interface FsButton {
        "disabled": boolean;
        "loading": boolean;
        /**
          * @default 'middle'
         */
        "size": ButtonSize;
        /**
          * @default 'secondary'
         */
        "type": ButtonType;
    }
    interface FsInput {
    }
    interface FsThemeProvider {
        "theme": Partial<Theme & { lightColor?: Partial<Theme['lightColor']>; darkColor?: Partial<Theme['darkColor']> }>;
    }
}
declare global {
    interface HTMLFsButtonElement extends Components.FsButton, HTMLStencilElement {
    }
    var HTMLFsButtonElement: {
        prototype: HTMLFsButtonElement;
        new (): HTMLFsButtonElement;
    };
    interface HTMLFsInputElement extends Components.FsInput, HTMLStencilElement {
    }
    var HTMLFsInputElement: {
        prototype: HTMLFsInputElement;
        new (): HTMLFsInputElement;
    };
    interface HTMLFsThemeProviderElement extends Components.FsThemeProvider, HTMLStencilElement {
    }
    var HTMLFsThemeProviderElement: {
        prototype: HTMLFsThemeProviderElement;
        new (): HTMLFsThemeProviderElement;
    };
    interface HTMLElementTagNameMap {
        "fs-button": HTMLFsButtonElement;
        "fs-input": HTMLFsInputElement;
        "fs-theme-provider": HTMLFsThemeProviderElement;
    }
}
declare namespace LocalJSX {
    interface FsButton {
        "disabled"?: boolean;
        "loading"?: boolean;
        /**
          * @default 'middle'
         */
        "size"?: ButtonSize;
        /**
          * @default 'secondary'
         */
        "type"?: ButtonType;
    }
    interface FsInput {
    }
    interface FsThemeProvider {
        "theme"?: Partial<Theme & { lightColor?: Partial<Theme['lightColor']>; darkColor?: Partial<Theme['darkColor']> }>;
    }
    interface IntrinsicElements {
        "fs-button": FsButton;
        "fs-input": FsInput;
        "fs-theme-provider": FsThemeProvider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fs-button": LocalJSX.FsButton & JSXBase.HTMLAttributes<HTMLFsButtonElement>;
            "fs-input": LocalJSX.FsInput & JSXBase.HTMLAttributes<HTMLFsInputElement>;
            "fs-theme-provider": LocalJSX.FsThemeProvider & JSXBase.HTMLAttributes<HTMLFsThemeProviderElement>;
        }
    }
}
